blank_issues_enabled: true
contact_links:
  - name: BitcoinPurple Core Security Policy
    url: https://github.com/bitcoinpurple/bitcoinpurple/blob/master/SECURITY.md
    about: View security policy
  - name: BitcoinPurple Core Developers
    url: https://bitcoincore.org
    about: BitcoinPurple Core homepage
