#ifndef BITCOINPURPLE_CHAINPARAMSSEEDS_H
#define BITCOINPURPLE_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoinpurple network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
};

static const uint8_t chainparams_seed_test[] = {
};
#endif // BITCOINPURPLE_CHAINPARAMSSEEDS_H
